# Generated by Django 4.1.4 on 2023-05-22 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(default=0)),
                ('taken_by', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('code', models.CharField(default='89', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('products', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(default='83', max_length=50),
        ),
    ]
