# Generated by Django 4.1.1 on 2023-02-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('ph', 'Philippines'), ('pl', 'Poland'), ('pt', 'Portugal'), ('br', 'Brazil'), ('cn', 'China'), ('dk', 'Denmark'), ('us', 'United States'), ('uk', 'United Kingdom'), ('gr', 'Greece'), ('ca', 'Canada'), ('ar', 'Argentina'), ('sa', 'Saudi Arabia'), ('be', 'Belgium')], default='pl', max_length=250),
        ),
    ]
